<a href="https://colab.research.google.com/github/NikhilRaj2004/Psp-assignment-/blob/main/2205A21032_A11_Res_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

student_data={
    "Roll No.":[101,102,103,104,105],
    "Telugu":[35,98,43,65,78],
    "English":[87,45,98,65,34],
    "Hindi":[45,26,78,45,67],
    "Maths":[45,56,67,78,89],
    "science":[23,34,45,56,76],
    "Social":[32,43,54,65,67]
}
data=pd.DataFrame(student_data)

Hall_Ticket_No=int(input("Enter the Roll No. : "))
index=data[data["Roll No."] == Hall_Ticket_No].index

score_card=data.loc[[index[0]]]
score_card.pop("Roll No.")
per=score_card.loc[index[[0]]].sum()*100/600

fail=score_card[score_card< 35].count()
no_of_fail_sub=fail.sum()
failed_sub=fail[fail==1].index

if(no_of_fail_sub>0):
  print("Status:Fail")
  print("Failed subjects:",failed_sub)

else:
  print("Status:Pass")
  print("Pass Percentage:",per)

score_card

Enter the Roll No. : 101
Status:Fail
Failed subjects: Index(['science', 'Social'], dtype='object')

   Telugu  English  Hindi  Maths  science  Social
0      35       87     45     45       23      32

In [2]:
import pandas as pd

student_data={
    "Roll No.":[101,102,103,104,105],
    "Telugu":[35,98,43,65,78],
    "English":[87,45,98,65,34],
    "Hindi":[45,26,78,45,67],
    "Maths":[45,56,67,78,89],
    "science":[23,34,45,56,76],
    "Social":[32,43,54,65,67]
}
data=pd.DataFrame(student_data)

Hall_Ticket_No=int(input("Enter the Roll No. : "))
index=data[data["Roll No."] == Hall_Ticket_No].index

score_card=data.loc[[index[0]]]
score_card.pop("Roll No.")
per=score_card.loc[index[[0]]].sum()*100/600

fail=score_card[score_card< 35].count()
no_of_fail_sub=fail.sum()
failed_sub=fail[fail==1].index

if(no_of_fail_sub>0):
  print("Status:Fail")
  print("Failed subjects:",failed_sub)

else:
  print("Status:Pass")
  print("Pass Percentage:",per)

score_card

Enter the Roll No. : 102
Status:Fail
Failed subjects: Index(['Hindi', 'science'], dtype='object')

   Telugu  English  Hindi  Maths  science  Social
1      98       45     26     56       34      43

In [3]:
import pandas as pd

student_data={
    "Roll No.":[101,102,103,104,105],
    "Telugu":[35,98,43,65,78],
    "English":[87,45,98,65,34],
    "Hindi":[45,26,78,45,67],
    "Maths":[45,56,67,78,89],
    "science":[23,34,45,56,76],
    "Social":[32,43,54,65,67]
}
data=pd.DataFrame(student_data)

Hall_Ticket_No=int(input("Enter the Roll No. : "))
index=data[data["Roll No."] == Hall_Ticket_No].index

score_card=data.loc[[index[0]]]
score_card.pop("Roll No.")
per=score_card.loc[index[[0]]].sum()*100/600

fail=score_card[score_card< 35].count()
no_of_fail_sub=fail.sum()
failed_sub=fail[fail==1].index

if(no_of_fail_sub>0):
  print("Status:Fail")
  print("Failed subjects:",failed_sub)

else:
  print("Status:Pass")
  print("Pass Percentage:",per)

score_card

Enter the Roll No. : 103
Status:Pass
Pass Percentage: Telugu      7.166667
English    16.333333
Hindi      13.000000
Maths      11.166667
science     7.500000
Social      9.000000
dtype: float64

   Telugu  English  Hindi  Maths  science  Social
2      43       98     78     67       45      54

In [4]:
import pandas as pd

student_data={
    "Roll No.":[101,102,103,104,105],
    "Telugu":[35,98,43,65,78],
    "English":[87,45,98,65,34],
    "Hindi":[45,26,78,45,67],
    "Maths":[45,56,67,78,89],
    "science":[23,34,45,56,76],
    "Social":[32,43,54,65,67]
}
data=pd.DataFrame(student_data)

Hall_Ticket_No=int(input("Enter the Roll No. : "))
index=data[data["Roll No."] == Hall_Ticket_No].index

score_card=data.loc[[index[0]]]
score_card.pop("Roll No.")
per=score_card.loc[index[[0]]].sum()*100/600

fail=score_card[score_card< 35].count()
no_of_fail_sub=fail.sum()
failed_sub=fail[fail==1].index

if(no_of_fail_sub>0):
  print("Status:Fail")
  print("Failed subjects:",failed_sub)

else:
  print("Status:Pass")
  print("Pass Percentage:",per)

score_card

Enter the Roll No. : 104
Status:Pass
Pass Percentage: Telugu     10.833333
English    10.833333
Hindi       7.500000
Maths      13.000000
science     9.333333
Social     10.833333
dtype: float64

   Telugu  English  Hindi  Maths  science  Social
3      65       65     45     78       56      65

In [5]:
import pandas as pd

student_data={
    "Roll No.":[101,102,103,104,105],
    "Telugu":[35,98,43,65,78],
    "English":[87,45,98,65,34],
    "Hindi":[45,26,78,45,67],
    "Maths":[45,56,67,78,89],
    "science":[23,34,45,56,76],
    "Social":[32,43,54,65,67]
}
data=pd.DataFrame(student_data)

Hall_Ticket_No=int(input("Enter the Roll No. : "))
index=data[data["Roll No."] == Hall_Ticket_No].index

score_card=data.loc[[index[0]]]
score_card.pop("Roll No.")
per=score_card.loc[index[[0]]].sum()*100/600

fail=score_card[score_card< 35].count()
no_of_fail_sub=fail.sum()
failed_sub=fail[fail==1].index

if(no_of_fail_sub>0):
  print("Status:Fail")
  print("Failed subjects:",failed_sub)

else:
  print("Status:Pass")
  print("Pass Percentage:",per)

score_card

Enter the Roll No. : 105
Status:Fail
Failed subjects: Index(['English'], dtype='object')

   Telugu  English  Hindi  Maths  science  Social
4      78       34     67     89       76      67